export interface IAntiquities {
	/**@description 古物代碼*/
	caseId: string;
	/**@description 圖片網址*/
	representImage: string;
	/**@description 古物名稱*/
	caseName: string;
	/**@description 古物級別*/
	assetsClassifyName: string;
	/**@description 古物年代*/
	descAge: string;
	/**@description 古物尺寸*/
	descSize: string;
	/**@description 古物材質*/
	descMaterial: string;
	/**@description 保存狀況*/
	reserveStatus?: string;
	/**@description 保管單位*/
	holder: string[];
	/**@description 主管機關*/
	manager: string[];
	/**@description 保存單位*/
	place: string[];
	/**@description 保存地址*/
	address: string[];
	/**@description 保存空間屬性*/
	saveSpace: string[];
	/**@description 保存空間文資身分*/
	saveSpaceId: string[];
	/**@description 保存環境*/
	environment: string;
	/**@description 古物件數*/
	amount: number;
	/**@description 資料來源*/
	dataSource: string;
}

export interface IMonuments {
	/**@description 古蹟代碼*/
	caseId: string;
	/**@description 圖片網址*/
	representImage: string;
	/**@description 古蹟名稱*/
	caseName: string;
	/**@description 古蹟級別*/
	assetsClassifyName: string;
	/**@description 古蹟種類*/
	assetsTypes: string[];
	/**@description 主管機關*/
	govInstitutionName: string;
	/**@description 古蹟地址*/
	belongAddress: string;
	/**@description 所在地區*/
	belongCity: string;
	/**@description 機關名稱*/
	govInstitution: string;
	/**@description 主管單位*/
	govDeptName: string;
	/**@description 機關電話*/
	govDeptPhone: string;
}
